### ISSUE TITLE
Lidar information error from rviz: "Could not transform from [base_scan] to [odom]"

### ISSUE THREAD

**Issue by devilbash** [kaiaai/kaia#1]
Good morning 
congratulations for the project it's fantastic!!
I've been trying for a few days to start the project and check the information from the lidar sensor, but in rviz I have the following error:
Could not transform from [base_scan] to [odom]
Would you have any ideas on how I can find the error? I'm sure I messed up somewhere

I recompiled the Kaaiai_telemetry project to check the logs a bit and it seems that they are published correctly! Do I need to activate any log in particular to get detailed information?

in attachment output of command "ros2 run tf2_tools view_frames"|
[frames_2024-08-22_07.17.08.pdf](https://github.com/user-attachments/files/16706949/frames_2024-08-22_07.17.08.pdf)

Is the problem on the base_scan node? from fames you can see these parameters at 0.0; in this case why I have this behavior
Buffer length: 0.0
Most recent transform: 0.0
Oldest transform: 0.0

also the command "ros2 run tf2_ros tf2_echo odom base_scan" returns the following error:
 Waiting for transform odom -> base_scan: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist

**Comment by kaiaai** [comment]
Hi devilbash,
  thank you for using the project, I do appreciate it!
I'm reading your issue, and it sounds you are way ahead of the crowd being proficient with ROS2.

Can you please let me know, so I can try replicating it
- which robot model are you using? Loki, Fido, Snoopy, Mini?
- which LiDAR model are you using?
- did you do your install using Docker or Ubuntu? If you are using Docker, what is (exactly) your command (Windows? Linux?) to launch the Docker image?
- what is (exactly) your Linux command to launch RViz?
- are you doing a virtual simulation or running a physical robot?
  - do you have a photo of your physical robot?

Can you please share a screenshot where you get the "Buffer length 0.0" and the rest of the messages?

That said, the "frame does not exist" error in RViz sometimes can be fixed by trying different settings for RViz Global Options -> Fixed Frame
![Untitled](https://github.com/user-attachments/assets/7a57dc33-e280-4c51-839e-f6b555fd3fcd)

**Comment by devilbash** [comment]
HI
unfortunately I'm not very expert in ROS2, I'm trying to learn for personal interest.
Your project, in addition to being very interesting, is also educationally valid for me as I am taking my first steps.

-actually a while ago, I assembled a fully cutstom [YABR ](http://www.brokking.net/yabr_main.html) self-balancing robot  and would like to expand its functionality with your project which is very modular.

-for now I'm only playing with the telemetry package developed to verify a lidar sensor purchased some time ago on aliexpres:
[Mini 360 gradi che vanno modellazione e mappatura robot ROS LiDAR scansione a 360 gradi TOF LiDAR](https://it.aliexpress.com/item/1005007119470172.html?spm=a2g0o.order_list.order_list_main.101.21ef3696DDg9zd&gatewayAdapt=glo2ita)
in the comments I found some projects to read the data exchanged on the serial port.
I'm adapting the github /devemin/UnknownLiDARMini _ M5StackCore2 This protocol looks like the Camsense X1 protocol 

-For the implementation I tried to do a custom ubuntu installation but I had problems with the version of some libraries so I'm using your Docker image with the following command
`docker run --name makerspet -it -v ros:/ros_ws -v home:/root --rm -p 8888:8888/udp -p 4430:4430/tcp -e DISPLAY=host.docker.internal:0.0 -e LIBGL_ALWAYS_INDIRECT=0 kaiaai/kaiaai:humble`
where home and ros are two volumes used for persistence of project customizations

-to start rviz use 
`ros2 launch kaiaai_bringup monitor_robot.launch.py ​​robot_model:=makerspet_loki` and configuring base_footprint from rviz global options works! :) A thousand thanks!
obviously I have to fix the lidar sensor driver but at least I'm starting to see some data and this is fantastic :) !!!

If you are interested as soon as the setup is finished, I can send you the project that I modified to expand the supported lidar sensors.

Thanks
Marco

**Comment by kaiaai** [comment]
I'd love to follow your project. Thank you for the Mini 360 link - I've seen it before, but I don't know who manufactures it.

About Camsense X1, this Arduino [library](https://github.com/kaiaai/LDS) supports Camsense X1 and there are other Camsense X1 pointers [here](https://github.com/kaiaai/awesome-2d-lidars).

**Comment by devilbash** [comment]
Thanks for the support I'm starting from a [github](https://github.com/devemin/UnknownLiDARMini_M5StackCore2/tree/main) that took inspiration from the repository you pointed out to me.
